from django.urls import path
from . import views

urlpatterns = [
path(''
, views.index, name= "books.index"),
path('list_books/', views.list_books, name= "books.list_books"),
path('<int:bookId>/', views.viewbook, name="books.view_one_book"),
path('aboutus/', views.aboutus, name="books.aboutus"),
path('html5/links', views.links_page, name="books.html5.links"),
path('html5/text/formatting', views.formatting_page, name="books.html5.formatting"),
path('html5/listing', views.listing_page, name="books.html5.listing"),
path('html5/tables', views.tables_page, name="books.html5.tables"),
path('search/', views.search_books, name="books.search"),
path('insert/', views.insert_books, name="books.insert"),
path('simple/query', views.simple_query, name="books.simple_query"),
path('complex/query', views.complex_query, name="books.complex_query"),
path('lab8/task1', views.lab8_task1, name="books.lab8.task1"),
path('lab8/task2', views.lab8_task2, name="books.lab8.task2"),
path('lab8/task3', views.lab8_task3, name="books.lab8.task3"),
path('lab8/task4', views.lab8_task4, name="books.lab8.task4"),
path('lab8/task5', views.lab8_task5, name="books.lab8.task5"),
path('lab8/task7', views.lab8_task7, name="books.lab8.task7"),
path('lab9/task1', views.lab9_task1, name="books.lab9.task1"),
path('lab9/task2', views.lab9_task2, name="books.lab9.task2"),
path('lab9/task3', views.lab9_task3, name="books.lab9.task3"),
path('lab9/task4', views.lab9_task4, name="books.lab9.task4"),
path('lab9/task5', views.lab9_task5, name="books.lab9.task5"),
path('lab9/task6', views.lab9_task6, name="books.lab9.task6"),

path('lab9_part1/listbooks', views.lab9_part1_listbooks, name="books.lab9_part1.listbooks"),
path('lab9_part1/addbook', views.lab9_part1_addbook, name="books.lab9_part1.addbook"),
path('lab9_part1/editbook/<int:id>', views.lab9_part1_editbook, name="books.lab9_part1.editbook"),
path('lab9_part1/deletebook/<int:id>', views.lab9_part1_deletebook, name="books.lab9_part1.deletebook"),

path('lab9_part2/listbooks', views.lab9_part2_listbooks, name="books.lab9_part2.listbooks"),
path('lab9_part2/addbook', views.lab9_part2_addbook, name="books.lab9_part2.addbook"),
path('lab9_part2/editbook/<int:id>', views.lab9_part2_editbook, name="books.lab9_part2.editbook"),
path('lab9_part2/deletebook/<int:id>', views.lab9_part2_deletebook, name="books.lab9_part2.deletebook"),

path('lab11/task1/addresses', views.lab11_task1_list_addresses, name="books.lab11.task1.list_addresses"),
path('lab11/task1/addresses/add', views.lab11_task1_add_address, name="books.lab11.task1.add_address"),
path('lab11/task1/addresses/edit/<int:id>', views.lab11_task1_edit_address, name="books.lab11.task1.edit_address"),
path('lab11/task1/addresses/delete/<int:id>', views.lab11_task1_delete_address, name="books.lab11.task1.delete_address"),
path('lab11/task1/students', views.lab11_task1_list_students, name="books.lab11.task1.list_students"),
path('lab11/task1/students/add', views.lab11_task1_add_student, name="books.lab11.task1.add_student"),
path('lab11/task1/students/edit/<int:id>', views.lab11_task1_edit_student, name="books.lab11.task1.edit_student"),
path('lab11/task1/students/delete/<int:id>', views.lab11_task1_delete_student, name="books.lab11.task1.delete_student"),

path('lab11/task2/addresses', views.lab11_task2_list_addresses, name="books.lab11.task2.list_addresses"),
path('lab11/task2/addresses/add', views.lab11_task2_add_address, name="books.lab11.task2.add_address"),
path('lab11/task2/addresses/edit/<int:id>', views.lab11_task2_edit_address, name="books.lab11.task2.edit_address"),
path('lab11/task2/addresses/delete/<int:id>', views.lab11_task2_delete_address, name="books.lab11.task2.delete_address"),
path('lab11/task2/students', views.lab11_task2_list_students, name="books.lab11.task2.list_students"),
path('lab11/task2/students/add', views.lab11_task2_add_student, name="books.lab11.task2.add_student"),
path('lab11/task2/students/edit/<int:id>', views.lab11_task2_edit_student, name="books.lab11.task2.edit_student"),
path('lab11/task2/students/delete/<int:id>', views.lab11_task2_delete_student, name="books.lab11.task2.delete_student"),

path('lab11/task3/products', views.lab11_task3_list_products, name="books.lab11.task3.list_products"),
path('lab11/task3/products/add', views.lab11_task3_add_product, name="books.lab11.task3.add_product"),
path('lab11/task3/products/edit/<int:id>', views.lab11_task3_edit_product, name="books.lab11.task3.edit_product"),
path('lab11/task3/products/delete/<int:id>', views.lab11_task3_delete_product, name="books.lab11.task3.delete_product"),
]
